### ISSUE TITLE
async.whilst solution doesn't compile

### ISSUE THREAD

**Issue by sindhus** [bulkan/async-you#32]
hi!

I tried out the async.whilst challenge and I couldn't get my code or the [given solution](https://github.com/bulkan/async-you/blob/master/exercises/whilst/solution/solution.js) to compile. I get this error:

```
➜  async-you git:(master) async-you run whilst.js
/usr/local/lib/node_modules/async-you/exercises/whilst/exercise.js:51
  if (!this.servers.length)
                   ^
TypeError: Cannot read property 'length' of undefined
    at Exercise.<anonymous> (/usr/local/lib/node_modules/async-you/exercises/whilst/exercise.js:51:20)
    at next (/usr/local/lib/node_modules/async-you/node_modules/workshopper-exercise/exercise.js:260:17)
    at Exercise.end (/usr/local/lib/node_modules/async-you/node_modules/workshopper-exercise/exercise.js:266:5)
    at Workshopper.end (/usr/local/lib/node_modules/async-you/node_modules/workshopper/workshopper.js:191:12)
    at Workshopper.done (/usr/local/lib/node_modules/async-you/node_modules/workshopper/workshopper.js:323:19)
    at Exercise.<anonymous> (/usr/local/lib/node_modules/async-you/node_modules/workshopper-exercise/exercise.js:149:14)
    at /usr/local/lib/node_modules/async-you/node_modules/workshopper-exercise/exercise.js:136:16
    at Exercise.<anonymous> (/usr/local/lib/node_modules/async-you/node_modules/workshopper-exercise/filecheck.js:10:14)
    at FSReqWrap.oncomplete (fs.js:99:15)
```

Thanks!

**Comment by alph486** [comment]
The whilst example does require an argument to the command line doesn't it? When using the `run` command you need to supply it. The error is probably just because it wasn't caught somewhere else first.

If you use the `async-you verify` command it will pass in default arguments to the application and ensure it produces the desired result.
